# Generated by Django 6.0.3 on 2026-05-08 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.URLField(default='https://images.unsplash.com/photo-1511578314322-379afb476865'),
            preserve_default=False,
        ),
    ]
